### PR TITLE
Update otel to 1.0.0-rc.1 and sync versioning

### PR DESCRIPTION
**Pull request by bryannaegele**
Update otel to v0.6 support. Add compatibility matrix.

I would have updated Ricardo's fork but I suck at that :)

### CODE REVIEW

**Comment by tsloughter** [comment]
@bryannaegele sorry I didn't merge this earlier, but can you update this to 1.0.0-rc.1 and then I can merge and release?

**Comment by bryannaegele** [comment]
@tsloughter do we expect any further changes that would affect this library? If not, should we just make it `"~> 1.0.0", allow_pre: true` so we don't have to cut a release for every change going forward? I'd like to figure out a strategy to not require mass, forced updates on every repo since updating this one to a pegged rc version means we have to do the same for phoenix, et al

**Comment by tsloughter** [comment]
Oh, I didn't know about `allow_pre`. If that works then I think that'd make the most sense, yes.

**Comment by bryannaegele** [comment]
@tsloughter Is this error being printed a bug? The test suite in this project uses the pid exporter but it's saying to include the exporter dep.

```Trace exporter module opentelemetry_exporter not found. Verify you have included the `opentelemetry_exporter` dependency.```

**Comment by tsloughter** [comment]
@bryannaegele oh, that might be because otlp is the default, so if an exporter isn't set before booting it'll output that message.

**Comment by bryannaegele** [comment]
> @bryannaegele oh, that might be because otlp is the default, so if an exporter isn't set before booting it'll output that message.

Ok. This is good to go then.

**Review by tsloughter — APPROVED** [review]

**Pull request merged**
