### PR TITLE
Add support for sampling

### LINKED ISSUE #3: Add sampler as option to setup
A sampler should be able to be passed to setup and then used in `handle_event` when creating the span.

Then give an example/test that does something with the repo name or how long the query took to decide if the span should be sampled or not.

### PR DESCRIPTION
**Pull request by dvic**
Closes #3

### CODE REVIEW

**Comment by dvic** [comment]
I'm not sure about what `sampler` should be, maybe just a function that has to return `:otel_sampler.t()`?

**Comment by dvic** [comment]
The option is now called `:sampler_for`, a function that accepts the Ecto Telemetry measurements and metadata and returns `{:sampler, :otel_sampler.t()} | :no_sampler`.

**Comment by dvic** [comment]
I'll probably change the option to just be `sampler` (no function) as I've opened a PR https://github.com/open-telemetry/opentelemetry-erlang/pull/260 that enables properly creating custom samplers (where the filtering can be done inside of those custom samplers).

**Comment by dvic** [comment]
~I've changed the option to just be `:sampler` - an optional `:otel_sampler.t()`.~

The type for the sampler option is now actually 
```elixir
:otel_sampler.t() | sampler_fun() | nil
```

with 
```elixir
  @type sampler_fun :: (telemetry_data() -> :otel_sampler.t() | nil)
  @type telemetry_data :: %{measurements: map(), meta: map()}
```

The reason for still having the option to use a function is that you might want to return a built-in sampler for certain requests (e.g., the `TraceIdRatioBased` sampler) so that the application monitoring systems (APM) can correctly calculate statistics based of this information. If there is always one custom sampler, an APM can't know which request was sampled and which one was not.

The test includes an example that creates a custom sampler and mentions https://github.com/open-telemetry/opentelemetry-erlang/pull/260.

**Comment by bryannaegele** [comment]
This PR is getting closed as part of archiving this repo. This project has moved to https://github.com/open-telemetry/opentelemetry-erlang-contrib/tree/main/instrumentation/opentelemetry_ecto.

Please open a discussion item in the contrib repo before reopening a PR as discussions with Tristan alluded to sampling support in instrumentation libraries being unnecessary; sampling strategy is settable through opentelemetry APIs.

**Pull request closed without merging**
